name: Discord Notification
on: [push, pull_request]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            **New ${{ github.event_name }}**
            Repository: ${{ github.repository }}
            By: ${{ github.actor }}
            ```
            ${{ github.event.head_commit.message }}
            ```
