name: Discord Notification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: '{{ EVENT_PAYLOAD.repository.full_name }} - New ${{ github.event_name }} by ${{ github.actor }}'
