name: Discord Notification
on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            **@everyone ${{ github.actor }} just pushed a new commit**
            ```
            ${{ github.event.head_commit.message }}
            ```
            Do a **git pull** within your local repository to get the latest changes.

